name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Compress to .osk
        run: |
          zip -r ruriruri.osk ./ -x='.git/*' -x='.github/*' -x='.git*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruriruri.osk
          path: ruriruri.osk